// Copyright (c) James Kassemi, SC, US. All rights reserved.

//! Arrow/Parquet schemas (stub).

use arrow::datatypes::{DataType, Field, Schema};
use std::sync::Arc;

/// Placeholder for OptionTrade schema.
pub fn option_trade_schema() -> Schema {
    Schema::new(vec![
        Field::new("contract", DataType::Utf8, false),
        Field::new("trade_uid", DataType::FixedSizeBinary(16), false),
        Field::new("contract_direction", DataType::Utf8, false),
        Field::new("strike_price", DataType::Float64, false),
        Field::new("underlying", DataType::Utf8, false),
        Field::new("trade_ts_ns", DataType::Int64, false),
        Field::new("price", DataType::Float64, false),
        Field::new("size", DataType::UInt32, false),
        Field::new(
            "conditions",
            DataType::List(Arc::new(Field::new("item", DataType::Int32, true))),
            true,
        ),
        Field::new("exchange", DataType::Int32, false),
        Field::new("expiry_ts_ns", DataType::Int64, false),
        Field::new("aggressor_side", DataType::Utf8, false),
        Field::new("class_method", DataType::Utf8, false),
        Field::new("aggressor_offset_mid_bp", DataType::Int32, true),
        Field::new("aggressor_offset_touch_ticks", DataType::Int32, true),
        Field::new("aggressor_confidence", DataType::Float64, true),
        Field::new("nbbo_bid", DataType::Float64, true),
        Field::new("nbbo_ask", DataType::Float64, true),
        Field::new("nbbo_bid_sz", DataType::UInt32, true),
        Field::new("nbbo_ask_sz", DataType::UInt32, true),
        Field::new("nbbo_ts_ns", DataType::Int64, true),
        Field::new("nbbo_age_us", DataType::UInt32, true),
        Field::new("nbbo_state", DataType::Utf8, true),
        Field::new("tick_size_used", DataType::Float64, true),
        Field::new("source", DataType::Utf8, false),
        Field::new("quality", DataType::Utf8, false),
        Field::new("watermark_ts_ns", DataType::Int64, false),
    ])
}

/// Placeholder for EquityTrade schema.
pub fn equity_trade_schema() -> Schema {
    Schema::new(vec![
        Field::new("symbol", DataType::Utf8, false),
        Field::new("trade_uid", DataType::FixedSizeBinary(16), false),
        Field::new("trade_ts_ns", DataType::Int64, false),
        Field::new("price", DataType::Float64, false),
        Field::new("size", DataType::UInt32, false),
        Field::new(
            "conditions",
            DataType::List(Arc::new(Field::new("item", DataType::Int32, true))),
            true,
        ),
        Field::new("exchange", DataType::Int32, false),
        Field::new("aggressor_side", DataType::Utf8, false),
        Field::new("class_method", DataType::Utf8, false),
        Field::new("aggressor_offset_mid_bp", DataType::Int32, true),
        Field::new("aggressor_offset_touch_ticks", DataType::Int32, true),
        Field::new("aggressor_confidence", DataType::Float64, true),
        Field::new("nbbo_bid", DataType::Float64, true),
        Field::new("nbbo_ask", DataType::Float64, true),
        Field::new("nbbo_bid_sz", DataType::UInt32, true),
        Field::new("nbbo_ask_sz", DataType::UInt32, true),
        Field::new("nbbo_ts_ns", DataType::Int64, true),
        Field::new("nbbo_age_us", DataType::UInt32, true),
        Field::new("nbbo_state", DataType::Utf8, true),
        Field::new("tick_size_used", DataType::Float64, true),
        Field::new("source", DataType::Utf8, false),
        Field::new("quality", DataType::Utf8, false),
        Field::new("watermark_ts_ns", DataType::Int64, false),
        Field::new("trade_id", DataType::Utf8, true),
        Field::new("seq", DataType::UInt64, true),
        Field::new("participant_ts_ns", DataType::Int64, true),
        Field::new("tape", DataType::Utf8, true),
        Field::new("correction", DataType::Int32, true),
        Field::new("trf_id", DataType::Utf8, true),
        Field::new("trf_ts_ns", DataType::Int64, true),
    ])
}

/// Placeholder for Nbbo schema.
pub fn nbbo_schema() -> Schema {
    Schema::new(vec![
        Field::new("instrument_id", DataType::Utf8, false),
        Field::new("quote_uid", DataType::FixedSizeBinary(16), false),
        Field::new("quote_ts_ns", DataType::Int64, false),
        Field::new("bid", DataType::Float64, false),
        Field::new("ask", DataType::Float64, false),
        Field::new("bid_sz", DataType::UInt32, false),
        Field::new("ask_sz", DataType::UInt32, false),
        Field::new("state", DataType::Utf8, false),
        Field::new("condition", DataType::Int32, true),
        Field::new("best_bid_venue", DataType::Int32, true),
        Field::new("best_ask_venue", DataType::Int32, true),
        Field::new("source", DataType::Utf8, false),
        Field::new("quality", DataType::Utf8, false),
        Field::new("watermark_ts_ns", DataType::Int64, false),
    ])
}

/// Aggregations schema.
pub fn aggregation_schema() -> Schema {
    let mut fields = vec![
        Field::new("symbol", DataType::Utf8, false),
        Field::new("window", DataType::Utf8, false),
        Field::new("window_start_ns", DataType::Int64, false),
        Field::new("window_end_ns", DataType::Int64, false),
    ];
    let metric_fields = [
        "underlying_price_open",
        "underlying_price_high",
        "underlying_price_low",
        "underlying_price_close",
        "underlying_dollar_value_total",
        "underlying_dollar_value_minimum",
        "underlying_dollar_value_maximum",
        "underlying_dollar_value_mean",
        "underlying_dollar_value_stddev",
        "underlying_dollar_value_skew",
        "underlying_dollar_value_kurtosis",
        "underlying_dollar_value_iqr",
        "underlying_dollar_value_mad",
        "underlying_dollar_value_cv",
        "underlying_dollar_value_mode",
        "underlying_dollar_value_bc",
        "underlying_dollar_value_dip_pval",
        "underlying_dollar_value_kde_peaks",
        "puts_below_intrinsic_pct",
        "puts_above_intrinsic_pct",
        "puts_aggressor_unknown_pct",
        "puts_classifier_touch_pct",
        "puts_classifier_at_or_beyond_pct",
        "puts_classifier_tick_rule_pct",
        "puts_classifier_unknown_pct",
        "puts_dadvv_total",
        "puts_dadvv_minimum",
        "puts_dadvv_maximum",
        "puts_dadvv_mean",
        "puts_dadvv_stddev",
        "puts_dadvv_skew",
        "puts_dadvv_kurtosis",
        "puts_dadvv_iqr",
        "puts_dadvv_mad",
        "puts_dadvv_cv",
        "puts_dadvv_mode",
        "puts_dadvv_bc",
        "puts_dadvv_dip_pval",
        "puts_dadvv_kde_peaks",
        "puts_signed_dadvv_total",
        "puts_signed_dadvv_minimum",
        "puts_signed_dadvv_maximum",
        "puts_signed_dadvv_mean",
        "puts_signed_dadvv_stddev",
        "puts_signed_dadvv_skew",
        "puts_signed_dadvv_kurtosis",
        "puts_signed_dadvv_iqr",
        "puts_signed_dadvv_mad",
        "puts_signed_dadvv_cv",
        "puts_signed_dadvv_mode",
        "puts_signed_dadvv_bc",
        "puts_signed_dadvv_dip_pval",
        "puts_signed_dadvv_kde_peaks",
        "puts_gadvv_total",
        "puts_gadvv_minimum",
        "puts_gadvv_maximum",
        "puts_gadvv_mean",
        "puts_gadvv_stddev",
        "puts_gadvv_skew",
        "puts_gadvv_kurtosis",
        "puts_gadvv_iqr",
        "puts_gadvv_mad",
        "puts_gadvv_cv",
        "puts_gadvv_mode",
        "puts_gadvv_bc",
        "puts_gadvv_dip_pval",
        "puts_gadvv_kde_peaks",
        "puts_signed_gadvv_total",
        "puts_signed_gadvv_minimum",
        "puts_signed_gadvv_maximum",
        "puts_signed_gadvv_mean",
        "puts_signed_gadvv_stddev",
        "puts_signed_gadvv_skew",
        "puts_signed_gadvv_kurtosis",
        "puts_signed_gadvv_iqr",
        "puts_signed_gadvv_mad",
        "puts_signed_gadvv_cv",
        "puts_signed_gadvv_mode",
        "puts_signed_gadvv_bc",
        "puts_signed_gadvv_dip_pval",
        "puts_signed_gadvv_kde_peaks",
        "calls_dollar_value",
        "calls_above_intrinsic_pct",
        "calls_aggressor_unknown_pct",
        "calls_classifier_touch_pct",
        "calls_classifier_at_or_beyond_pct",
        "calls_classifier_tick_rule_pct",
        "calls_classifier_unknown_pct",
        "calls_dadvv_total",
        "calls_dadvv_minimum",
        "calls_dadvv_maximum",
        "calls_dadvv_mean",
        "calls_dadvv_stddev",
        "calls_dadvv_skew",
        "calls_dadvv_kurtosis",
        "calls_dadvv_iqr",
        "calls_dadvv_mad",
        "calls_dadvv_cv",
        "calls_dadvv_mode",
        "calls_dadvv_bc",
        "calls_dadvv_dip_pval",
        "calls_dadvv_kde_peaks",
        "calls_signed_dadvv_total",
        "calls_signed_dadvv_minimum",
        "calls_signed_dadvv_maximum",
        "calls_signed_dadvv_mean",
        "calls_signed_dadvv_stddev",
        "calls_signed_dadvv_skew",
        "calls_signed_dadvv_kurtosis",
        "calls_signed_dadvv_iqr",
        "calls_signed_dadvv_mad",
        "calls_signed_dadvv_cv",
        "calls_signed_dadvv_mode",
        "calls_signed_dadvv_bc",
        "calls_signed_dadvv_dip_pval",
        "calls_signed_dadvv_kde_peaks",
        "calls_gadvv_total",
        "calls_gadvv_minimum",
        "calls_gadvv_q1",
        "calls_gadvv_q2",
        "calls_gadvv_q3",
        "calls_gadvv_maximum",
        "calls_gadvv_mean",
        "calls_gadvv_stddev",
        "calls_gadvv_skew",
        "calls_gadvv_kurtosis",
        "calls_gadvv_iqr",
        "calls_gadvv_mad",
        "calls_gadvv_cv",
        "calls_gadvv_mode",
        "calls_gadvv_bc",
        "calls_gadvv_dip_pval",
        "calls_gadvv_kde_peaks",
        "calls_signed_gadvv_total",
        "calls_signed_gadvv_minimum",
        "calls_signed_gadvv_q1",
        "calls_signed_gadvv_q2",
        "calls_signed_gadvv_q3",
        "calls_signed_gadvv_maximum",
        "calls_signed_gadvv_mean",
        "calls_signed_gadvv_stddev",
        "calls_signed_gadvv_skew",
        "calls_signed_gadvv_kurtosis",
        "calls_signed_gadvv_iqr",
        "calls_signed_gadvv_mad",
        "calls_signed_gadvv_cv",
        "calls_signed_gadvv_mode",
        "calls_signed_gadvv_bc",
        "calls_signed_gadvv_dip_pval",
        "calls_signed_gadvv_kde_peaks",
    ];
    for name in metric_fields.iter() {
        fields.push(Field::new(*name, DataType::Float64, true));
    }
    Schema::new(fields)
}

/// Slim overlay schema for derived Greeks outputs.
pub fn greeks_overlay_schema() -> Schema {
    Schema::new(vec![
        Field::new("trade_uid", DataType::FixedSizeBinary(16), false),
        Field::new("trade_ts_ns", DataType::Int64, false),
        Field::new("contract", DataType::Utf8, false),
        Field::new("underlying", DataType::Utf8, false),
        Field::new("delta", DataType::Float64, true),
        Field::new("gamma", DataType::Float64, true),
        Field::new("vega", DataType::Float64, true),
        Field::new("theta", DataType::Float64, true),
        Field::new("iv", DataType::Float64, true),
        Field::new("greeks_flags", DataType::UInt32, false),
        Field::new("nbbo_bid", DataType::Float64, true),
        Field::new("nbbo_ask", DataType::Float64, true),
        Field::new("nbbo_bid_sz", DataType::UInt32, true),
        Field::new("nbbo_ask_sz", DataType::UInt32, true),
        Field::new("nbbo_ts_ns", DataType::Int64, true),
        Field::new("nbbo_age_us", DataType::UInt32, true),
        Field::new("nbbo_state", DataType::Utf8, true),
        Field::new("engine_version", DataType::Utf8, false),
        Field::new("treasury_curve_date", DataType::Utf8, true),
        Field::new("treasury_curve_source_date", DataType::Utf8, true),
        Field::new("enriched_at_ns", DataType::Int64, false),
        Field::new("run_id", DataType::Utf8, false),
    ])
}
